config/routes.rb
RhAshRails3::Application.routes.draw do

  # match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :method => :get, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  # get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :jour_academiques do
    collection do
      get :index_pour_annee
      put :index_pour_annee   #Quand l'invocation vient du formulaire de saisie de l'année
      patch :index_pour_annee   #Quand l'invocation vient du formulaire de saisie de l'année
    end
  end

  root :to => 'pages#index'
  
  # ressources représentant des types : 
  resources :type_projets do
    collection do
      get :new_categorie
    end
  end
  resources :type_budgets
  resources :type_id_externes
  
  devise_for :personnes

  #resources :affectation_projets
  
  resources :personnes do
    collection do
      get :droits
      get :resume_heures_collaborateurs_sem1
      get :resume_heures_collaborateurs_sem2
      get :resume_heures_professeurs_sem1
      get :resume_heures_professeurs_sem2
      get :new_personne_fictive
    end
    member do 
      get :resume_heures_annee_precedente
      # get :old_resume_heures
      # put :old_resume_heures
      get :resume_heures
      put :resume_heures #Quand l'invocation vient du formulaire de saisie de l'année
      patch :resume_heures #Quand l'invocation vient du formulaire de saisie de l'année
      get :edit_roles
      put :update_roles
      patch :update_roles
      get :gestion_desideratas
      get :resume_conso
      get :resume_conso_graph_data
      get :enregistrer_desiderata
      get :edit_horaire
      put :update_horaire
      patch :update_horaire
    end
    resources :contrats do
      collection do
        get :historique
      end
    end
    resources :cahier_charge_assistants
    resources :affectation_projets
    resources :affectation_projet_academiques, :controller=>:affectation_projets 
    resources :plage_horaire_saisies do 
      collection do
        get :semaine
        get :jours
        get :add
        get :add_mois
        get :cloner_semaine_precedente
      end
    end
  end
  
  resources :plage_contractuelles do
    collection do
      get :resume_heures
      put :resume_heures
      patch :resume_heures
      put :ajuster_report_heures_sup
      patch :ajuster_report_heures_sup
      put :ajuster_report_heures_vacances
      patch :ajuster_report_heures_vacances
      get :get_calendrier_details
      get :heures_supplementaires
      post :annuler_heures_supplementaires
    end
  end
  
  resources :contrats do
    collection do
      get :stats
      get :index_global
      get :nouvel_engagement
      get :update_engagement
      get :create_engagement
      get :destroy_engagement
    end
  end
  
  resources :projets do
    member do 
      get :resume_conso
      get :resume_conso_graph_data
      get :activer
      get :desactiver
      get :archiver
      get :desarchiver
    end
    collection do
     get :essai
   end
    resources :budgets
    resources :affectation_projets do
      member do
        get :activer
        get :desactiver
        get :supprimer_heures_saisies
      end
    end
    resources :affectation_projet_academiques, :controller=>:affectation_projets 
  end

  
  # match '/personnes/:personne_id/plage_horaire_saisies/:year/:month' => 'plage_horaire_saisies#mois', :as => :calendar, :method => :get#, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  # match 'configuration', :to => "pages#configuration", :as => "configuration", :method => :get
  # match 'enseignement',  :to => "pages#enseignement",  :as => "enseignement", :method => :get
  # match 'exportation_heures_sagex', :to => "pages#exportation_heures_sagex", :as => "exportation_heures_sagex", :method => :get
  # match 'do_exportation_heures_sagex', :to => "pages#do_exportation_heures_sagex", :as => "do_exportation_heures_sagex", :method => :post
    
  get '/personnes/:personne_id/plage_horaire_saisies/:year/:month' => 'plage_horaire_saisies#mois', :as => :calendar#, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get 'configuration', :to => "pages#configuration", :as => "configuration"
  get 'enseignement',  :to => "pages#enseignement",  :as => "enseignement"
  get 'exportation_heures_sagex', :to => "pages#exportation_heures_sagex", :as => "exportation_heures_sagex"
  post 'do_exportation_heures_sagex', :to => "pages#do_exportation_heures_sagex", :as => "do_exportation_heures_sagex"
  
  # AJAX specific routes
  # match '/affectation_projets/get_engagements_select/:personne_id/:projet_id', :to => "affectation_projets#get_engagements_select", :method => :get
  # match '/affectation_projets/project_specific_fields/:projet_id/:personne_id', :to => "affectation_projets#project_specific_fields", :method => :get
  # match '/affectation_projets/get_consommation_graph_data', :to => "affectation_projets#get_consommation_graph_data", :method => :get
  # match '/affectation_projets/:id/get_details', :to => "affectation_projets#get_details", :method => :get
  # match '/get_type_projet_field', :to => "projets#get_type_fields", :method => :get
  
  get '/affectation_projets/get_engagements_select/:personne_id/:projet_id', :to => "affectation_projets#get_engagements_select"
  get '/affectation_projets/project_specific_fields/:projet_id/:personne_id', :to => "affectation_projets#project_specific_fields"
  get '/affectation_projets/get_consommation_graph_data', :to => "affectation_projets#get_consommation_graph_data"
  get '/affectation_projets/:id/get_details', :to => "affectation_projets#get_details"
  get '/get_type_projet_field', :to => "projets#get_type_fields"
  
  # Legacy ajax routes
  # match '/cahier_charge_assistant/heures_modifiees/:id', :to => "cahier_charge_assistants#heures_modifiees"

  # TODO : refacor and nest into personnes
  resources :personne_prives
  
  resources :variables
  resources :salles
  resources :personne_charge_enseignements
  resources :charge_enseignements
  resources :road_map_actions
  resources :road_maps do
    collection do
      get :doit
      get :dupliquer
      get :supprimer
      get :creer_projets_labos
      get :reset_heures
      get :reset_heures_dune_personne
      get :reset_global_des_heures
    end
  end

  resources :interet_unites
  #resources :cahier_charge_assistants
  #match 'cahier_charge_assistant/heures_modifiees/:id', :controller => 'cahier_charge_assistants', :action => 'heures_modifiees'
  #match 'cahier_charge_assistants/:id', :controller => 'cahier_charge_assistants', :action => 'show'
  #match 'cahier_charge_assistants/:id/edit', :controller => 'cahier_charge_assistants', :action => 'edit'
  resources :charge_assistants
  resources :axe_strategiques
  #map.connect 'personne_prives/:id/edit', :controller => 'personne_prives', :action => 'edit'
  #map.connect 'personnes/update_assignement/:id', :controller => 'personnes', :action => 'ajout_assignement', :id => :id
  resources :date_evenement_personne
  
  resources :charges do
    collection do 
      get :charge_professeurs_global
      get :charge_des_assistants
      get :charge_des_professeurs
      get :get_prev_details
      get :get_details
      get :get_personne_details
      get :update_effectiv_flag
      get :create_charge_effective
      get :liste_eduardo
      get :change_assistanat_reconnu
      get :graphe_affectations
      get :graphe_affectations_data
    end
  end
  
  resources :unite_enseignements do
    member do
      get :charges
      get :nouvelle_charge
      get :change_assistanat_reconnu
      get :inc_groupes_th
      get :inc_groupes_th
      get :dec_groupes_th
      get :inc_groupes_labo
      get :dec_groupes_labo     
      post :create_charge
      get :edit_charge
      put :update_charge
      patch :update_charge
      get :destroy_charge         
      get :up_groupe   
    end
  end
  
  resources :charge_effectives
  resources :type_activites
  resources :module_unites
  resources :modules
  resources :desiderata_projets
  resources :type_categories
  resources :suivis
  resources :type_engagements
  resources :contrat_mensuels
  resources :mois
  resources :constantes
  resources :cst_heures
  resources :desideratas
  resources :competence_domaines
  resources :drag_drop
  resources :niveau_competences
  resources :type_personnes
  resources :type_periodes
  resources :evenement_personnes
  resources :type_evenement_personnes
  resources :data_annee_civiles
  resources :annee_civiles
  resources :periodes
  resources :type_unite_enseignements
  resources :orientations
  resources :filieres
  resources :annee_academiques
  resources :departements

  # Ajout du module de planification
  resources :configurations_planifications
  resources :planifications do
    collection do
      get 'getRessources', :defaults => { :format => 'json' }
      get 'getProjets', :defaults => { :format => 'json' }
    end
  end

  resources :notifications
  resources :commentaires
  resources :jalons



  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # TODO : supprimer ça une fois le refactoring terminé pour rendre l'application RESTful
  # match ':controller(/:action(/:id(.:format)))', :method => :get
  get ':controller(/:action(/:id(.:format)))'

end

app/controllers/projets_controller.rb
# -*- encoding : utf-8 -*-
class ProjetsController < ApplicationController

  load_and_authorize_resource

  before_filter :set_form_data, :only => [:new, :create, :update, :edit]

  def index
    #@types_projets = TypeProjet.select
    @projets = Projet.all
    respond_with(@projets)
  end

  def show
    @projet = Projet.find(params[:id])
    @affectations=@projet.affectation_projets
    @total_heures_saisies =@affectations.joins(:plage_horaire_saisies).sum(:heures) 
    @charge_globale = @affectations.sum(:charge_horaire) 

# puts
# puts @projet.inspect
# puts

    respond_with(@projet)
  end

  def new
    
    # si le type de projet n'est pas renseigné, on retourne un formulaire de choix
    if params[:classe_projet].nil? || 
       params[:type_projet_id].nil? ||
       params[:classe_projet].empty? ||
       params[:type_projet_id].empty?
      render :choix_type
      return
    end
    
    case params[:classe_projet]
      when "Projet"
        @projet = Projet.new
      when "ProjetAcademique" 
        if Variable.phase_planification_enseignement?
          raise "Impossible en ce moment: phase de planification des enseignements en cours "
        else
          @projet = ProjetAcademique.new
          @projet.annee_academique_realisation=AnneeAcademique.courante
          @annee_academique_id = AnneeAcademique.courante.id
          @unites_potentielles = UniteEnseignement.unites_annee_souhaitee(@annee_academique_id)
        end
      when "ProjetEnseignement" 
        if Variable.phase_planification_enseignement?
          raise "Impossible en ce moment: phase de planification des enseignements en cours "
        else
          @projet = ProjetEnseignement.new
          @projet.annee_academique_realisation=AnneeAcademique.courante
          @projet.id_interne=""
          @annee_academique_id = AnneeAcademique.courante.id
          @unites_potentielles = UniteEnseignement.unites_annee_souhaitee(@annee_academique_id)
        end
      when "These"
        @projet = These.new
        @annee_academique_id = AnneeAcademique.courante.id
        @unites_potentielles = UniteEnseignement.unites_annee_souhaitee(@annee_academique_id)
      else
        raise "classe de projet inconnue !"
    end
    @projet.type_projet_id = params[:type_projet_id]
    @projet.id_sagex=@projet.type_projet.compte_sagex_par_defaut
    
    respond_with(@projet)
  end

  def edit
    @projet = Projet.find(params[:id])
    if @projet.kind_of? ProjetAcademique
      @projet.id_interne=@projet.identifiant_interne_to_update
      @annee_academique_id = @projet.annee_academique_realisation.id
      if @projet.kind_of? ProjetEnseignement 
        @unites_potentielles = UniteEnseignement.unites_annee_souhaitee(@annee_academique_id)
      end
    end
  end

  def create
    
    case params[:classe_projet]
      when "Projet"
        @projet = Projet.new
      when "ProjetAcademique"
        @projet = ProjetAcademique.new
      when "ProjetEnseignement"
        @projet = ProjetEnseignement.new
      when "These"
        @projet = These.new
      else
        raise "classe de projet inconnue !"
    end

#    @projet.attributes = params[:projet]
    @projet.attributes = projet_params
    @projet.est_actif=true
    
    if @projet.kind_of? ProjetEnseignement 
      no_groupe=@projet.id_interne  # Groupe de l'unité d'enseignement: A, B, etc..
      @projet.id_interne=@projet.identifiant_interne(no_groupe)
      @projet.id_externe=@projet.identifiant_externe(no_groupe)
      @projet.date_debut=@projet.unite_enseignement.periode.date_debut-30
      @projet.date_fin=@projet.unite_enseignement.periode.date_fin+15
    elsif @projet.kind_of? ProjetAcademique
      @projet.id_interne=@projet.id_interne+ " "+ @projet.annee_academique_realisation.annee 
      @projet.id_externe=""
    end
      
    if @projet.save
      redirect_to(projet_path(@projet))
    else
      render :action => "new"
    end
  end

  def update
    @projet = Projet.find(params[:id])
    @projet.update_attributes(params[:projet])
    
    if @projet.kind_of? ProjetEnseignement 
      no_groupe=@projet.id_interne  # Groupe de l'unité d'enseignement: A, B, etc..
      @projet.id_interne=@projet.identifiant_interne(no_groupe)
      @projet.id_externe=@projet.identifiant_externe(no_groupe)
    elsif @projet.kind_of? ProjetAcademique
      @projet.id_interne=@projet.id_interne+ " "+ @projet.annee_academique_realisation.annee 
      @projet.id_externe=""
    end

    @projet.save
    respond_with(@projet, :location => @projet.becomes(Projet))
  end

  def destroy
    @projet = Projet.find(params[:id])
    if @projet.affectation_projets.empty?
      @projet.destroy
      flash[:notice]="Suppression réalisée avec succès!"
      respond_with(@projet, :location => @projet.becomes(Projet))
    else 
      flash[:alert]="Suppression impossible - Le projet possède des affectations"
      respond_with(@projet, :location => @projet.becomes(Projet))
    end
  end
  
  def activer
    @projet = Projet.find(params[:id])
    @projet.est_actif=true
    if @projet.save
      redirect_to(projet_path(@projet)) 
    end
  end
  
  def desactiver
    @projet = Projet.find(params[:id])
    @projet.est_actif=false
    if @projet.save
      redirect_to(projet_path(@projet))
    end
  end
  
  def archiver
    @projet = Projet.find(params[:id])
    @projet.est_archive=true
    if @projet.save
      redirect_to(projet_path(@projet))
    end
  end
  
  def desarchiver
    @projet = Projet.find(params[:id])
    @projet.est_archive=false
    if @projet.save
      redirect_to(projet_path(@projet))
    end
  end
  
  def get_type_fields
  
    render :partial => "type_projet_field", :locals => {:genre => params[:genre]}
  
    require 'unite_enseignements_controller'
  end
  
  def resume_conso
    render :partial => "resume_conso", :locals => {:projet => @projet}
  end
  
  def resume_conso_graph_data
    res_proj = []
    @projet.affectation_projets.each do |ap|
      res_ap = []
      ap.plage_horaire_saisies.order(:debut).each do |plage_horaire| 
        if res_ap.count > 0 && plage_horaire.debut.at_midnight.to_i*1000 == res_ap.last[0]
          res_ap.last[1] += plage_horaire.heures
        else
          res_ap << [plage_horaire.debut.at_midnight.to_i*1000, plage_horaire.heures]
        end
      end
      res_proj << {"label" => ap.personne.display_name, "data" => res_ap}
    end
    
    respond_to do |format|
      format.js do
        render :text => res_proj.to_json
      end
    end
  end
  
  def essai
    redirect_to(personnes_path)
    flash[:notice]="Le routage a fonctionné !!"
  end

  def isChef?(personne)
    self.chef_id == personne.id
  end
  
private

  def set_form_data
    @type_projets = TypeProjet.feuilles(TypeProjet.order(:nom))
    @chefs_potentiels = Personne.personnes_actives_de_linstitut.sort_by(&:display_name)
  end

  # strong parameters de Rails >4.0
  def projet_params
    params.require(:projet).permit(:classe_projet, :type_projet_id)
  end

end

app/helpers/projets_helper.rb
# -*- encoding : utf-8 -*-
module ProjetsHelper
end

app/views/projets/_actions.html.haml
- if @projet && !@projet.new_record?
  = "Actions sur #{@projet.display_name}"
  = menu_item "Détails du projet", projet_path(@projet), :show, :projets, can?(:show, @projet), params
  = menu_item "Supprimer le projet", projet_path(@projet), :destroy, :projets, can?(:destroy, @projet), params, :method => :delete, data: {:confirm => "Etes-vous sûr ?"}
  - if !@projet.is_archive?
    = menu_item "Modifier le projet", edit_projet_path(@projet), :edit, :projets, can?(:edit, @projet), params
    = menu_item "Archiver le projet", archiver_projet_path(@projet), :archiver, :projets, can?(:edit, @projet), params, data: {:confirm => "Etes-vous sûr ?"}
    - if @projet.est_actif
      = menu_item "Desactiver le projet", desactiver_projet_path(@projet), :desactiver, :projets, can?(:edit, @projet), params, data: {:confirm => "Etes-vous sûr ?"}
    - if !@projet.est_actif
      = menu_item "Activer le projet", activer_projet_path(@projet), :activer, :projets, can?(:edit, @projet), params, data: {:confirm => "Etes-vous sûr ?"}
    = menu_item "Affecter une personne", new_projet_affectation_projet_path(@projet, :vient_de => :projet), :new, :affectation_projets, can?(:new, @projet.affectation_projets.build), params
  - if @projet.is_archive?
    = menu_item "Ré-actualiser le projet", desarchiver_projet_path(@projet), :archiver, :projets, can?(:edit, @projet), params, data: {:confirm => "Etes-vous sûr ?"}

= "Actions globales sur les projets"
= menu_item "Liste des projets", projets_path, :index, :projets, can?(:read, Projet), params
= menu_item "Ajouter un projet", new_projet_path, :new, :projets, can?(:create, Projet), params
%br

app/views/projets/_budget_fields.html.haml
.fields
  = f.inputs :class => "budget_inputs" do
    = f.input :horaire, :label => "Budget horaire", :hint => "Nombre d'heures"
    = f.input :financier, :label => "Budget financier", :hint => "CHF"
    = f.input :type_budget, :include_blank => " - Choisissez un type de budget"
    -#= f.input :prioritaire, :collection => Budget.prioritaires_possibles, :include_blank => " - Choisissez un budget prioritaire -"
    .top_right= link_to_remove_fields "Supprimer", f

app/views/projets/_form.html.haml
= semantic_form_for(@projet, :as => :projet, :url => @projet.becomes(Projet)) do |pb|
  =# @projet.errors
  = pb.inputs do
    = hidden_field_tag "classe_projet", @projet.class
    = pb.hidden_field :type_projet_id
    - if !@projet.kind_of? ProjetAcademique
      = pb.input :id_interne
      = pb.input :id_sagex
      - if @projet.type_projet.type_id_externe_id
        = pb.input :id_externe, :label => "Id #{@projet.type_projet.type_id_externe.display_name}"
      = pb.input :description
      = pb.input :chef, :collection => @chefs_potentiels, :include_blank => " - Choisissez un chef de projet -"
      - if !@projet.type_projet.date_debut_indeterminee
        = pb.input :date_debut, :as => :calendar
      - if !@projet.type_projet.date_fin_indeterminee
        = pb.input :date_fin, :as => :calendar
      %br
      - if @projet.type_projet.affichage_possible_charge_en_jours
        = pb.input :affichage_charge_en_jours, :label => "Afficher les charges horaires et heures saisies en jours-heures-minutes"
      .header_02="Budgets"
      .budgets
        = pb.semantic_fields_for :budgets do |bb|
          = render "budget_fields", :f => bb
        = link_to_add_fields "Ajouter un budget", pb, :budgets
    - if @projet.kind_of? ProjetAcademique
      - if @projet.kind_of? ProjetEnseignement
        = pb.input :unite_enseignement, :collection => @unites_potentielles, :include_blank => false
        = pb.input :id_interne, :collection => ["A", "B", "C", "D", "E"], :label => "Groupe [A, B, ..]", :include_blank => false
        = pb.input :id_sagex, :label => "Mapping Sagex"
        = pb.hidden_field :annee_academique_realisation_id
        - if mode.eql?("update")
          - if !@projet.type_projet.date_debut_indeterminee
            = pb.input :date_debut, :as => :calendar
          - if !@projet.type_projet.date_fin_indeterminee
            = pb.input :date_fin, :as => :calendar
        %br
        - if @projet.type_projet.affichage_possible_charge_en_jours
          = pb.input :affichage_charge_en_jours, :label => "Afficher les charges horaires et heures saisies en jours-heures-minutes"
      - elsif @projet.kind_of? These
        = pb.input :id_interne
        = pb.input :id_sagex
        - if @projet.type_projet.type_id_externe_id
          = pb.input :id_externe, :label => "Id #{@projet.type_projet.type_id_externe.display_name}"
        = pb.input :chef_id, :collection => @chefs_potentiels, :include_blank => " - Choisissez un chef de projet -"
        = pb.input :annee_academique_realisation, :include_blank => " - Choisissez une année académique -"
        = pb.input :nom_etudiant, :label => "Nom de l'étudiant"
        %br
        - if @projet.type_projet.affichage_possible_charge_en_jours
          = pb.input :affichage_charge_en_jours, :label => "Afficher les charges horaires et heures saisies en jours-heures-minutes"
        .header_02="Budgets"
        .budgets
          = pb.semantic_fields_for :budgets do |bb|
            = render "budget_fields", :f => bb 
      - else 
        = pb.input :id_interne, :hint => "Le nom saisi sera automatiquement complété par l'année académique (p.e.: 2010-2011)"
        = pb.input :id_sagex, :label => "Mapping Sagex"
        = pb.hidden_field :annee_academique_realisation_id
        - if !@projet.type_projet.date_debut_indeterminee
          = pb.input :date_debut, :as => :calendar
        - if !@projet.type_projet.date_fin_indeterminee
          = pb.input :date_fin, :as => :calendar
        %br
        - if @projet.type_projet.affichage_possible_charge_en_jours
          = pb.input :affichage_charge_en_jours, :label => "Afficher les charges horaires et heures saisies en jours-heures-minutes"
  = pb.buttons do
    = pb.commit_button "Valider"

app/views/projets/_resume_conso.html.haml
.affectation_consommation_graph_global{:"data-projet_id" => projet.id}

app/views/projets/choix_type.html.haml
- content_for :head do
  = javascript_include_tag "new_projet"
%h1= "Nouveau Projet"
%br

= semantic_form_for(:projet, :url => projets_path) do |f|
  = f.inputs do
    %li{:class => "required", :id => "classe_projet_input"}
      %label{:for => "classe_projet"}= "Genre de projet"
      = select_tag :classe_projet, options_for_select([["- Choisissez un genre de projet", ""]]+Projet.genres_projets)
    
    = render :partial => "type_projet_field", :locals => {:genre => nil}
    
  /= f.buttons do
  /  = f.commit_button "Valider"

  = f.actions do
    = f.action :submit, :label => "Valider"

app/views/projets/edit.html.haml
- content_for :left_menu do
  = render :partial => 'actions'
%h1= "Modification d'un projet"
%br
= render :partial => "form", :locals => {:mode=>"update"}

app/views/projets/show.html.haml
- content_for :left_menu do
  = render :partial => 'actions'
- content_for :head do
  = javascript_include_tag("flot/jquery.flot")
  = javascript_include_tag("flot/jquery.flot.stack")
  = javascript_include_tag("flot/jquery.flot.threshold")
  = javascript_include_tag("affectation_details")
  = javascript_include_tag("show_projet")
  
%h1
  = "Projet #{@projet.display_name}"
%h2
  - if !@projet.en_activite?
    = image_tag('inactif.png')
    - if @projet.hors_date?
      - if !@projet.est_actif
        = " Hors date & désactivé"
      - else
        = " Hors date"
    - else
      = " Désactivé"
  - if @projet.is_archive?
    = image_tag('archive.png')
    = " Projet archivé"
%ol.info
  = show_value "Id Interne", @projet.id_interne
  = show_value "Id Sagex", @projet.id_sagex
  - if @projet.type_projet.type_id_externe_id
    = show_value "Id "+ @projet.type_projet.type_id_externe.display_name, @projet.id_externe
  = show_value "Genre de projet", @projet.genre
  = show_value "Type de projet", @projet.type_projet
  - if @projet.en_activite?
    = show_image("Projet en activité", "ok.png", "16x16" )
  - else
    = show_image("Projet en activité", "inactif.png", "16x16" )
  = show_value "Description", @projet.description
  = show_value "Chef", @projet.chef
  - if @projet.kind_of? These
    = show_value "Nom de l'étudiant", @projet.nom_etudiant
  - if @projet.kind_of? ProjetEnseignement
    = show_value "Unité d'enseignement", @projet.try(:unite_enseignement)
  - if @projet.kind_of? ProjetAcademique
    = show_value "Année académique", @projet.annee_academique_realisation
  - if !@projet.type_projet.date_debut_indeterminee
    = show_value "Date de début",d(@projet.date_debut)
  - else
    = show_value "Date de début", "indéterminée"
  - if !@projet.type_projet.date_fin_indeterminee
    = show_value "Date de fin",d(@projet.date_fin)
  - else
    = show_value "Date de fin", "indéterminée"
  .clear
  .spacer
  .header_02= "Budgets (#{@projet.budgets.count})"
  - if @projet.budgets.count > 0
    - @projet.budgets.each do |budget|
      .budget
        %ol
          = show_value "Horaire", budget.horaire+(budget.horaire.empty? ? "" : " Heures")
          = show_value "Financier", budget.financier+(budget.financier.empty? ? "" : " CHF")
          = show_value "Type", budget.type_budget
          -# = show_value "Prioritaire", budget.prioritaire
          .clear
  - else
    %li= "Aucun budget"
  .clear 
  .spacer 
  .header_02= "Charges / Consommation"
  .resume_global
    .affectation_label= "Résumé Consommation"
    - if @charge_globale > 0 
      - if (@total_heures_saisies.to_f / @charge_globale.to_f) > 1.0
        - barclass = " progressbar_depassement"
      - else
        - barclass = ""
      #charge_globale_progressbar{:class => "affectation_progressbar#{barclass}",:"data-charge" => @charge_globale, :"data-heures_saisies" => @total_heures_saisies}
      -#.affectation_ratio1= "#{sprintf("%0.01f", @total_heures_saisies)}"
      .affectation_ratio1= heure_en_format_heures_minutes(@total_heures_saisies)
      .affectation_ratio2= "/"
      -#.affectation_ratio3= "#{sprintf("%0.01f", @charge_globale)}"
      .affectation_ratio3= heure_en_format_heures_minutes(@charge_globale)
    - else
      %div{:style => "width: 35%; float: left"}= "&nbsp;".html_safe
      -#.affectation_ratio1= "#{sprintf("%0.01f", @total_heures_saisies)}"
      .affectation_ratio1= heure_en_format_heures_minutes(@total_heures_saisies) 
      .affectation_ratio2= "&nbsp;".html_safe
      .affectation_ratio3= "&nbsp;".html_safe
    %button.affectation_button_global= "Détails"
    .clear
    .affectation_details{:"data-projet_id" => @projet.id}
  .spacer
  .ruler
  - if @projet.affectation_projets.count > 0
    = render :partial => "affectation_projets/liste_affectations", :locals => {:m => @projet, :affectations => @projet.affectation_projets.all}
  - else
    %li= "Aucune personne affectée"
  .clear
  .spacer
  - if can?(:new, @projet.affectation_projets.build)
    - if !@projet.is_archive?
      = link_to "Affecter une personne supplémentaire", new_projet_affectation_projet_path(@projet, :vient_de => :projet)
  
  