config/routes.rb
RhAshRails3::Application.routes.draw do

  # match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :method => :get, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  # get '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  resources :jour_academiques do
    collection do
      get :index_pour_annee
      put :index_pour_annee   #Quand l'invocation vient du formulaire de saisie de l'année
      patch :index_pour_annee   #Quand l'invocation vient du formulaire de saisie de l'année
    end
  end

  root :to => 'pages#index'
  
  # ressources représentant des types : 
  resources :type_projets do
    collection do
      get :new_categorie
    end
  end
  resources :type_budgets
  resources :type_id_externes
  
  devise_for :personnes

  #resources :affectation_projets
  
  resources :personnes do
    collection do
      get :droits
      get :resume_heures_collaborateurs_sem1
      get :resume_heures_collaborateurs_sem2
      get :resume_heures_professeurs_sem1
      get :resume_heures_professeurs_sem2
      get :new_personne_fictive
    end
    member do 
      get :resume_heures_annee_precedente
      # get :old_resume_heures
      # put :old_resume_heures
      get :resume_heures
      put :resume_heures #Quand l'invocation vient du formulaire de saisie de l'année
      patch :resume_heures #Quand l'invocation vient du formulaire de saisie de l'année
      get :edit_roles
      put :update_roles
      patch :update_roles
      get :gestion_desideratas
      get :resume_conso
      get :resume_conso_graph_data
      get :enregistrer_desiderata
      get :edit_horaire
      put :update_horaire
      patch :update_horaire
    end
    resources :contrats do
      collection do
        get :historique
      end
    end
    resources :cahier_charge_assistants
    resources :affectation_projets
    resources :affectation_projet_academiques, :controller=>:affectation_projets 
    resources :plage_horaire_saisies do 
      collection do
        get :semaine
        get :jours
        get :add
        get :add_mois
        get :cloner_semaine_precedente
      end
    end
  end
  
  resources :plage_contractuelles do
    collection do
      get :resume_heures
      put :resume_heures
      patch :resume_heures
      put :ajuster_report_heures_sup
      patch :ajuster_report_heures_sup
      put :ajuster_report_heures_vacances
      patch :ajuster_report_heures_vacances
      get :get_calendrier_details
      get :heures_supplementaires
      post :annuler_heures_supplementaires
    end
  end
  
  resources :contrats do
    collection do
      get :stats
      get :index_global
      get :nouvel_engagement
      get :update_engagement
      get :create_engagement
      get :destroy_engagement
    end
  end
  
  resources :projets do
    member do 
      get :resume_conso
      get :resume_conso_graph_data
      get :activer
      get :desactiver
      get :archiver
      get :desarchiver
    end
    collection do
     get :essai
   end
    resources :budgets
    resources :affectation_projets do
      member do
        get :activer
        get :desactiver
        get :supprimer_heures_saisies
      end
    end
    resources :affectation_projet_academiques, :controller=>:affectation_projets 
  end

  
  # match '/personnes/:personne_id/plage_horaire_saisies/:year/:month' => 'plage_horaire_saisies#mois', :as => :calendar, :method => :get#, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  # match 'configuration', :to => "pages#configuration", :as => "configuration", :method => :get
  # match 'enseignement',  :to => "pages#enseignement",  :as => "enseignement", :method => :get
  # match 'exportation_heures_sagex', :to => "pages#exportation_heures_sagex", :as => "exportation_heures_sagex", :method => :get
  # match 'do_exportation_heures_sagex', :to => "pages#do_exportation_heures_sagex", :as => "do_exportation_heures_sagex", :method => :post
    
  get '/personnes/:personne_id/plage_horaire_saisies/:year/:month' => 'plage_horaire_saisies#mois', :as => :calendar#, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}
  get 'configuration', :to => "pages#configuration", :as => "configuration"
  get 'enseignement',  :to => "pages#enseignement",  :as => "enseignement"
  get 'exportation_heures_sagex', :to => "pages#exportation_heures_sagex", :as => "exportation_heures_sagex"
  post 'do_exportation_heures_sagex', :to => "pages#do_exportation_heures_sagex", :as => "do_exportation_heures_sagex"
  
  # AJAX specific routes
  # match '/affectation_projets/get_engagements_select/:personne_id/:projet_id', :to => "affectation_projets#get_engagements_select", :method => :get
  # match '/affectation_projets/project_specific_fields/:projet_id/:personne_id', :to => "affectation_projets#project_specific_fields", :method => :get
  # match '/affectation_projets/get_consommation_graph_data', :to => "affectation_projets#get_consommation_graph_data", :method => :get
  # match '/affectation_projets/:id/get_details', :to => "affectation_projets#get_details", :method => :get
  # match '/get_type_projet_field', :to => "projets#get_type_fields", :method => :get
  
  get '/affectation_projets/get_engagements_select/:personne_id/:projet_id', :to => "affectation_projets#get_engagements_select"
  get '/affectation_projets/project_specific_fields/:projet_id/:personne_id', :to => "affectation_projets#project_specific_fields"
  get '/affectation_projets/get_consommation_graph_data', :to => "affectation_projets#get_consommation_graph_data"
  get '/affectation_projets/:id/get_details', :to => "affectation_projets#get_details"
  get '/get_type_projet_field', :to => "projets#get_type_fields"
  
  # Legacy ajax routes
  # match '/cahier_charge_assistant/heures_modifiees/:id', :to => "cahier_charge_assistants#heures_modifiees"

  # TODO : refacor and nest into personnes
  resources :personne_prives
  
  resources :variables
  resources :salles
  resources :personne_charge_enseignements
  resources :charge_enseignements
  resources :road_map_actions
  resources :road_maps do
    collection do
      get :doit
      get :dupliquer
      get :supprimer
      get :creer_projets_labos
      get :reset_heures
      get :reset_heures_dune_personne
      get :reset_global_des_heures
    end
  end

  resources :interet_unites
  #resources :cahier_charge_assistants
  #match 'cahier_charge_assistant/heures_modifiees/:id', :controller => 'cahier_charge_assistants', :action => 'heures_modifiees'
  #match 'cahier_charge_assistants/:id', :controller => 'cahier_charge_assistants', :action => 'show'
  #match 'cahier_charge_assistants/:id/edit', :controller => 'cahier_charge_assistants', :action => 'edit'
  resources :charge_assistants
  resources :axe_strategiques
  #map.connect 'personne_prives/:id/edit', :controller => 'personne_prives', :action => 'edit'
  #map.connect 'personnes/update_assignement/:id', :controller => 'personnes', :action => 'ajout_assignement', :id => :id
  resources :date_evenement_personne
  
  resources :charges do
    collection do 
      get :charge_professeurs_global
      get :charge_des_assistants
      get :charge_des_professeurs
      get :get_prev_details
      get :get_details
      get :get_personne_details
      get :update_effectiv_flag
      get :create_charge_effective
      get :liste_eduardo
      get :change_assistanat_reconnu
      get :graphe_affectations
      get :graphe_affectations_data
    end
  end
  
  resources :unite_enseignements do
    member do
      get :charges
      get :nouvelle_charge
      get :change_assistanat_reconnu
      get :inc_groupes_th
      get :inc_groupes_th
      get :dec_groupes_th
      get :inc_groupes_labo
      get :dec_groupes_labo     
      post :create_charge
      get :edit_charge
      put :update_charge
      patch :update_charge
      get :destroy_charge         
      get :up_groupe   
    end
  end
  
  resources :charge_effectives
  resources :type_activites
  resources :module_unites
  resources :modules
  resources :desiderata_projets
  resources :type_categories
  resources :suivis
  resources :type_engagements
  resources :contrat_mensuels
  resources :mois
  resources :constantes
  resources :cst_heures
  resources :desideratas
  resources :competence_domaines
  resources :drag_drop
  resources :niveau_competences
  resources :type_personnes
  resources :type_periodes
  resources :evenement_personnes
  resources :type_evenement_personnes
  resources :data_annee_civiles
  resources :annee_civiles
  resources :periodes
  resources :type_unite_enseignements
  resources :orientations
  resources :filieres
  resources :annee_academiques
  resources :departements

  # Ajout du module de planification
  resources :configurations_planifications
  resources :planifications do
    collection do
      get 'getRessources', :defaults => { :format => 'json' }
      get 'getProjets', :defaults => { :format => 'json' }
    end
  end

  resources :notifications
  resources :commentaires
  resources :jalons



  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # TODO : supprimer ça une fois le refactoring terminé pour rendre l'application RESTful
  # match ':controller(/:action(/:id(.:format)))', :method => :get
  get ':controller(/:action(/:id(.:format)))'

end

app/helpers/unite_enseignements_helper.rb
# -*- encoding : utf-8 -*-
module UniteEnseignementsHelper
end

app/views/unite_enseignements/_actions.html.haml
- if @unite_enseignement && !@unite_enseignement.new_record?
  = "Actions sur #{@unite_enseignement.display_name_short}"
  = menu_item "Détails de l'unite", unite_enseignement_path(@unite_enseignement), :show, :unite_enseignements, can?(:show, @unite_enseignement), params
  = menu_item "Supprimer l'unite", unite_enseignement_path(@unite_enseignement), :destroy, :unite_enseignements, can?(:destroy, @unite_enseignement), params, :method => :delete, data: {:confirm => "Etes-vous sûr de vouloir supprimer l'unite #{@unite_enseignement.display_name_short}?"}
  = menu_item "Modifier l'unite", edit_unite_enseignement_path(@unite_enseignement), :edit, :unite_enseignements, can?(:edit, @unite_enseignement), params
  = menu_item "Charges associées à l'unité", charges_unite_enseignement_path(@unite_enseignement), :charges, :unite_enseignements, can?(:edit, @unite_enseignement), params
%br
%br
= "Actions globales sur les unités d'enseignement"
= menu_item "Liste des unités", unite_enseignements_path, :index, :unite_enseignements, can?(:read, :enseignement), params
= menu_item "Ajouter une unité", new_unite_enseignement_path, :new, :unite_enseignements, can?(:manage, :enseignement), params
%br

app/views/unite_enseignements/_form.html.haml
- if mode.eql?("new")
  = set_onload_remote_function(:url=>{:action=>'creation_orientation_draggable', :mode=>"new", :unite=> @unite_enseignement})
- else
  = set_onload_remote_function(:url=>{:action=>"annee_mise_a_jour"}, :with=>"'id_annee_academique=' + #{@annees_academiques.first.id} + '&id_unite=' + #{@unite_enseignement.id}+ '&index=' + '#{false}'")
= semantic_form_for(@unite_enseignement, :html => {:multipart => true}) do |f|
  = f.inputs do
    = f.input :reconductible, :label => "Cours actif ", :as => :boolean
    = f.input :assistanat_reconnu, :label => "Assistanat reconnu", :as => :boolean
    = f.input :abreviation, :label => "Abreviation ", :input_html => {:size => 10, :maxlength => 10} 
    = f.input :nom, :label => "Nom ", :input_html => {:size => 40, :maxlength => 40} 
    = f.input :texte, :label => "Commentaire éventuel ", :input_html => {:size => 40, :maxlength => 40}  
    = f.input :type_unite_enseignement, :label => "Type de l'enseignement ", :collection => @type_unite_enseignements, :label_method => :type_unite, :include_blank => " - Choisissez un type d'enseignement -"
    = f.input :periode,  :label => "Période d'enseignement", :collection => @periodes, :label_method => :descriptif, :include_blank => " - Choisissez une période -"
    = f.input :chargeExamen, :label => "Charge d'examen ", :input_html => {:size => 5, :maxlength => 5} 
    = f.input :personne, :label => "Responsable de l'unité ", :collection => @professeurs, :label_method => :initiale, :include_blank => " - Choisissez un professeur -"
    %ol.info
    %br
    = f.input :nbGroupesTh, :label => "Théorie - Nombre de groupes", :input_html => {:size => 5, :maxlength => 5} 
    = f.input :nbGroupesLab, :label => "Laboratoire - Nombre de groupes", :input_html => {:size => 5, :maxlength => 5}
    %ol.info
    %br
    = f.input :nbPeriodesTheoriquesSemaine, :label => "Charge théorique", :input_html => {:size => 5, :maxlength => 5}, :hint =>  "Périodes/semaine"
    = f.input :nbPeriodesPratiquesSemaine, :label => "Charge laboratoire", :input_html => {:size => 5, :maxlength => 5} , :hint =>  "Périodes/semaine"  
    %br
    = f.input :coursBloc, :label => "Cours bloc ", :as => :boolean
    = f.input :nbPeriodesTheoriquesTotal, :label => "Théorie - Total périodes", :input_html => {:size => 5, :maxlength => 5}, :hint =>  "Pour cours bloc seulement"
    = f.input :nbPeriodesPratiquesTotal, :label => "Laboratoire - Total périodes", :input_html => {:size => 5, :maxlength => 5}, :hint =>  "Pour cours bloc seulement" 
    %ol.info
 
    %table
      %tr
        %td
          %h2 Liens sur les orientations
          /
            \......................................................................................................
            Première boîte représentant les orientations rattachées à l'unité
            \.......................................................................................................
          #orientations_concernees.boiteOrientationDeplacable
            %p
              %b Orientations rattachées à l'unité:
            - @orientations_concernees.each do |orientation|
              %span.cadre_orientations_concernees{:id => orientation}
                = orientation
                %br
          /
            \......................................................................................................
            Deuxième boîte représentant les orientations non rattachées
            \.......................................................................................................
          #orientations_non_concernees.boiteOrientationDeplacable
            %p
              %b Autres orientations disponibles:
            - @orientations_non_concernees.each do |orientation|
              %span.cadre_orientations_non_concernees{:id => orientation}
                = orientation
                %br
          .clear
          = image_tag "ajax-loader.gif", :id=>"wait_icon", :style=>"display:none"
  

  -#  \......................................................................................................
  -#  Permet le déplacement de la première boîte à la deuxième
  -#  \.......................................................................................................
  = drop_receiving_element "orientations_non_concernees",                                                                            |
    :url=>{:action=>"deplacement_orientation", :target=>"orientations_non_concernees", :class=>"cadre_orientations_non_concernees"}, |
    :before => "Element.toggle('wait_icon')",                                                                                        |
    :complete => "Element.toggle('wait_icon')",                                                                                      |
    :accept=>'cadre_orientations_concernees'                                                                                         |
  -#  \......................................................................................................
  -#  Permet le déplacement de la deuxième boîte à la première
  -#  \.......................................................................................................
  = drop_receiving_element "orientations_concernees",                                                                            |
    :url=>{:action=>"deplacement_orientation", :target=>"orientations_concernees", :class=>"cadre_orientations_concernees"}, |
    :before => "Element.toggle('wait_icon')",                                                                                        |
    :complete => "Element.toggle('wait_icon')",                                                                                      |
    :accept=>'cadre_orientations_non_concernees'                                                                                         |
  -#/
  -#  \......................................................................................................
  -#  Permet de mettre à jour le champ des périodes en fonction de l'année choisie ainsi que la liste des orientations
  -#  \.......................................................................................................
  #result_validation
  = observe_field 'unite_annee_academique',                                                                                                            |
    :url=>{:action=>"annee_mise_a_jour"},                                                                                                              |
    :before => "Element.toggle('wait_icon')",                                                                                                          |
    :complete => "Element.toggle('wait_icon')",                                                                                                        |
    :with => "'id_annee_academique=' + escape(value) +                                                                                                 |
    '&orientations_non_concernees=' + Element.findChildren($('orientations_non_concernees'), null, false, 'span').map(function(elt){return elt.id;}) + |
      '&orientations_concernees=' + Element.findChildren($('orientations_concernees'), null, false, 'span').map(function(elt){return elt.id;}) +       |
      '&id_unite=' + #{@unite_enseignement.id}+                                                                                                        |
    '&index=' + '#{false}'"                                                                                                                            |
  %br
  %ol.info
  %br  
  = f.buttons do
    = f.commit_button "Valider" 
    | #{link_to 'Retour', unite_enseignements_path}

app/views/unite_enseignements/_liste_charges.haml
%ol.info
  - if typeGroupe.eql?('T')
    - tabGroupes=@tabGroupesTheorie
    - if @unite_enseignement.taux_charge_theorie_OK?
      = show_image("Prise en charge à 100%", "ok.png", "32x32" )
    - else
      = show_image("Prise en charge à 100%", "echec_icone.gif", "32x32" )
  - else
    - tabGroupes=@tabGroupesLab
    - if @unite_enseignement.taux_charge_labo_OK?
      = show_image("Prise en charge à 100%", "ok.png", "32x32" )
    - else
      = show_image("Prise en charge à 100%", "echec_icone.gif", "32x32" )
  - tabGroupes.each do |noGroupe|
    %br
    %h4= "Groupe #{noGroupe}"
    - if !noGroupe.eql?('A')
      = link_to image_tag('report_up_small.png'), up_groupe_unite_enseignement_path(@unite_enseignement, :groupe => noGroupe, :type_groupe => typeGroupe)
    %table
      %tr
        %th{:style => "text-align:left; width: 90px"}="Enseignement"
        %th{:style => "text-align:left; width: 40px"}="Taux"
        %th{:style => "text-align:left; width: 40px"}="Heures"
        %th{:style => "text-align:left; width: 90px"}="Assistanat"
        %th{:style => "text-align:left; width: 40px"}="Taux"
        %th{:style => "text-align:left; width: 40px"}="Heures"
        %th{:style => "text-align:left; width: 40px"}
        %th{:style => "text-align:left; width: 40px"}
      %tr
        %td
          =link_to image_tag('report_add_small.png'), nouvelle_charge_unite_enseignement_path(@unite_enseignement, :groupe => noGroupe, :type_groupe => typeGroupe, :mode=>'enseignement')
        %td="#{@unite_enseignement.taux_charge_pour_groupe(noGroupe, 'enseignement', typeGroupe)}%"
        %td="#{@unite_enseignement.heures_charge_pour_groupe(noGroupe, 'enseignement', typeGroupe)}"
        %td
          =link_to image_tag('report_add_small.png'), nouvelle_charge_unite_enseignement_path(@unite_enseignement, :groupe => noGroupe, :type_groupe => typeGroupe, :mode=>'assistanat')
        %td="#{@unite_enseignement.taux_charge_pour_groupe(noGroupe, 'assistanat', typeGroupe)}%"
        %td="#{@unite_enseignement.heures_charge_pour_groupe(noGroupe, 'assistanat', typeGroupe)}"
      - @unite_enseignement.charges_associees_pour_groupe(noGroupe, 'enseignement', typeGroupe).each do |charge|
        %tr
          %td= h charge.personne.initiale
          %td= h charge.taux
          %td= h charge.heures
          %td= h "-"
          %td= h "-"
          %td= h "-"
          %td= link_to image_tag('report_edit_small.png'), edit_charge_unite_enseignement_path(@unite_enseignement, :charge_id => charge.id, :mode=>'enseignement')
          %td= link_to image_tag('destroy_small.png'), destroy_charge_unite_enseignement_path(@unite_enseignement, :charge_id => charge.id, :mode=>'enseignement'), data: {:confirm => 'Suppression de la charge - Etes-vous sûr?'}
      - @unite_enseignement.charges_associees_pour_groupe(noGroupe, 'assistanat', typeGroupe).each do |charge|
        %tr
          %td= h "-"
          %td= h "-"
          %td= h "-"
          %td= h charge.personne.initiale
          %td= h charge.taux
          %td= h charge.heures
          %td= link_to image_tag('report_edit_small.png'), edit_charge_unite_enseignement_path(@unite_enseignement, :charge_id => charge.id, :mode=>'assistanat')
          %td= link_to image_tag('destroy_small.png'), destroy_charge_unite_enseignement_path(@unite_enseignement, :charge_id => charge.id, :mode=>'assistanat'), data: {:confirm => 'Suppression de la charge - Etes-vous sûr?'}
    %br

app/views/unite_enseignements/_liste_unites.html.haml
- row = 0
%table{:class => "liste_ue"}      
  %tr
    %th{:style => "text-align:left; width: 80px"} Sigle
    %th{:style => "text-align:left; width: 90px"} Orientations
    %th{:style => "text-align:left; width: 25px"} Th
    %th{:style => "text-align:left; width: 25px"} Lab
    %th{:style => "text-align:center; width: 30px"} Option
    %th{:style => "text-align:center; width: 30px"} Master
    %th{:style => "text-align:center; width: 50px"} Grp Th
    %th{:style => "text-align:center; width: 50px"} Grp Lab
    %th{:style => "text-align:left; width: 70px"} Période
    %th{:style => "text-align:center; width: 50px"} Examen
    %th{:style => "text-align:center; width: 50px"} Assistanat
    %th{:style => "text-align:left; width: 25px"} 
    %th{:style => "text-align:left; width: 25px"} 
    %th{:style => "text-align:left; width: 25px"} 
  - for unite_enseignement in unite_enseignements
    %div{:id => "unite_enseignement_#{unite_enseignement.id}"}
      - row += 1
      %tr{:style => (row % 2 == 0) ? "background-color:#DDDDDD" : "background-color:#C2D0DA"}
        - if unite_enseignement.reconductible
          %td{:class =>"sigle"}= link_to unite_enseignement.abreviation, unite_enseignement_path(unite_enseignement)
        - else 
          %td{:class =>"sigle", :style => "color: #1060F0; background-color: #00CCCC"  }= link_to unite_enseignement.abreviation, unite_enseignement_path(unite_enseignement)
        %td= h unite_enseignement.texte_orientations_concernees
        %td{:style => "text-align:center"}= h unite_enseignement.nbPeriodesTheoriquesSemaine
        %td{:style => "text-align:center"}= h unite_enseignement.nbPeriodesPratiquesSemaine
        - if unite_enseignement.isOption?
          %td{:style => "text-align:center"}= h "O"
        - else
          %td{:style => "text-align:center"}= h ""
        - if unite_enseignement.isMaster?
          %td{:style => "text-align:center"}= h "M"
        - else
          %td{:style => "text-align:center"}= h ""
        %td{:style => "text-align:center"}= h unite_enseignement.nbGroupesTh
        %td{:style => "text-align:center"}= h unite_enseignement.nbGroupesLab
        %td{:style => "text-align:center"}= h unite_enseignement.periode.idPeriode
        %td{:style => "text-align:center"}= h unite_enseignement.chargeExamen
        - if !unite_enseignement.assistanat_reconnu
          %td{:style => "text-align:center;color: #1060F0; background-color: #00CCCC"}= "supprimé"
        - else
          %td{:style => "text-align:center"}= h ""            
        %td
          %table
            %tr
              - if can? :manage, :enseignement
                %td{:style => "background-color:#FFFFFF"}= link_to image_tag('report_edit_small.png'), edit_unite_enseignement_path(unite_enseignement)
                %td{:style => "background-color:#FFFFFF"}= link_to image_tag('supprimer_small_2.png'), unite_enseignement, data: {:confirm => 'Etes-vous sûr de vouloir effacer cette unité d\'enseignement ?'},   :method => :delete
                %td{:style => "background-color:#FFFFFF"}= link_to 'Charges', charges_unite_enseignement_path(unite_enseignement)
  %tr
%br
.clear
= image_tag "ajax-loader.gif", :id=>"wait_icon", :style=>"display:none"

app/views/unite_enseignements/charges.html.haml
- content_for :left_menu do
  = render :partial => 'actions'
.header_02= "Charges de l'unité d'enseignement #{@unite_enseignement.abreviation}"

%br
%ol.info
  - if !@unite_enseignement.reconductible
    = show_image("Unité active", "no_big_icone.png", "16x16" )
  %table
    %tr
      %th{:style => "text-align:left; width: 150px"}=""
      %th{:style => "text-align:left; width: 50px"}=""
      %th{:style => "text-align:left; width: 30px"}=""
    %tr
      %td{:style => "font-weight: bold; font-size: 14px; text-align:left"}= "Assistanat reconnu"
      %td
        - if @unite_enseignement.assistanat_reconnu
          = image_tag("ok.png")
        - else
          = image_tag("no_big_icone.png")
      %td= link_to image_tag('change_medium_icone.png'), change_assistanat_reconnu_unite_enseignement_path(@unite_enseignement)
  %br
  %h4= "Nombre de groupes"
  %table
    %tr
      %th{:style => "text-align:left; width: 130px"}=""
      %th{:style => "text-align:left; width: 10px"}=""
      %th{:style => "text-align:left; width: 10px"}=""
      %th{:style => "text-align:left; width: 100px"}=""
      %th{:style => "text-align:left; width: 120px"}=""
      %th{:style => "text-align:left; width: 10px"}=""
      %th{:style => "text-align:left; width: 10px"}=""
    %tr
      %td{:style => "font-weight: bold; font-size: 13px; text-align:left"}= "Théorie: #{@unite_enseignement.nbGroupesTh.to_s} groupe(s)"
      %td= link_to image_tag('plus_medium_icone.png'), inc_groupes_th_unite_enseignement_path(@unite_enseignement)
      - if @unite_enseignement.nbGroupesTh >= 1
        %td= link_to image_tag('minus_medium_icone.png'), dec_groupes_th_unite_enseignement_path(@unite_enseignement)
      - else
        %td= ""
      %td=""
      %td{:style => "font-weight: bold; font-size: 13px; text-align:left"}= "Labo: #{@unite_enseignement.nbGroupesLab.to_s} groupe(s)"
      %td= link_to image_tag('plus_medium_icone.png'), inc_groupes_labo_unite_enseignement_path(@unite_enseignement)
      - if @unite_enseignement.nbGroupesLab >= 1
        %td= link_to image_tag('minus_medium_icone.png'), dec_groupes_labo_unite_enseignement_path(@unite_enseignement) 
      - else
        %td= ""
  %br
  %h4= "Dotation #{@unite_enseignement.nbPeriodesTheoriquesSemaine.to_s} - #{@unite_enseignement.nbPeriodesPratiquesSemaine.to_s}"
  - if @unite_enseignement.coursBloc
    = show_image("Cours bloc", "ok.png", "16x16" )
    %br
    %h4 Charge totale en périodes 
    = show_value "Théorie", @unite_enseignement.nbPeriodesTheoriquesTotal
    = show_value "Labo", @unite_enseignement.nbPeriodesPratiquesTotal
%br
%br
.header_02= "Théorie"
= render :partial => 'liste_charges', :locals => {:typeGroupe=>'T'}
%br
%br
.header_02= "Laboratoire"
= render :partial => 'liste_charges', :locals => {:typeGroupe=>'L'}

app/views/unite_enseignements/edit.html.haml
- content_for :left_menu do
  = render :partial => 'actions'
%h1= "Modifier l'unité d'enseignement #{@unite_enseignement.display_name_short}"
%br
= render :partial => "form", :locals => {:mode=>"edit"}

app/views/unite_enseignements/index.html.haml
- content_for :left_menu do
  - if @comes_from && @comes_from=='charges'
    = render :partial => 'charges/actions' 
  - else
    = render :partial => 'unite_enseignements/actions' 
%br
%h1 Unités d'enseignement
%br
= render(:partial => 'liste_unites', :locals => {:unite_enseignements => @unite_enseignements_actives})
%br
%h1 Unités d'enseignement archivées
%br
= render(:partial => 'liste_unites', :locals => {:unite_enseignements => @unite_enseignements_inactives}) 